server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    zipkin:
      endpoint: 0.0.0.0:9411

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

query_frontend: {}
